# 1. Usamos una imagen ligera de Node
FROM node:18-alpine

# 2. Creamos la carpeta de trabajo dentro del contenedor
WORKDIR /app

# 3. Copiamos los archivos de dependencias
COPY package*.json ./

# 4. Instalamos las librerías
RUN npm install --production

# 5. Copiamos el resto del código (index.js)
COPY . .

# 6. Exponemos el puerto 3000
EXPOSE 3000

# 7. Comando para iniciar
CMD ["node", "index.js"]